env:
  - K8S_VERSION=v1.11
  - K8S_VERSION=v1.12.3
  
services:
  - docker

script:
  - docker build -t ccme2e -f Dockerfile-e2e .
  - docker run --rm -e ONEANDONE_API_KEY=$ONEANDONE_API_KEY -e K8S_VERSION=$K8S_VERSION ccme2e

branches:
  only:
    - master