FROM golang:1.10-alpine
WORKDIR /go/src/github.com/1and1internet/oneandone-cloud-controller-manager
COPY . .
RUN go test -c ./test/e2e
RUN apk add --no-cache ca-certificates \
  curl \
  terraform \
  ansible

RUN curl -L -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
  chmod +x /usr/local/bin/kubectl

# ENV ONEANDONE_API_KEY xxx
CMD ["./e2e.test", "-test.v", "-test.timeout", "30m"]

