FROM golang:1.10-alpine
WORKDIR /go/src/github.com/1and1internet/oneandone-cloud-controller-manager
COPY . .
RUN apk add --no-cache ca-certificates \
  curl \
  terraform \
  ansible

RUN curl -L -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
  chmod +x /usr/local/bin/kubectl

# ENV CLOUD_PANEL_API_KEY xxx
CMD ["go", "test", "-v", "-timeout", "30m", "./test/e2e"]

